from .agent_01 import PROMPT_AGENT_01_PSYCHOLOGY_INSTRUCTION
from .agent_02 import PROMPT_AGENT_02_INSTRUCTION
from .agent_03 import PROMPT_AGENT_03_INSTRUCTION
from .agent_04 import PROMPT_AGENT_04_INSTRUCTION
from .agent_05 import PROMPT_AGENT_05_TASK_DECOMPOSITION
from .agent_06 import PROMPT_AGENT_06_DEEP_ANALYSIS
from .agent_07 import PROMPT_AGENT_07_IKIGAI, PROMPT_AGENT_07_IKIGAI_ANALYSIS

__all__ = [
    "PROMPT_AGENT_01_PSYCHOLOGY_INSTRUCTION",
    "PROMPT_AGENT_02_INSTRUCTION",
    "PROMPT_AGENT_03_INSTRUCTION",
    "PROMPT_AGENT_04_INSTRUCTION",
    "PROMPT_AGENT_05_TASK_DECOMPOSITION",
    "PROMPT_AGENT_06_DEEP_ANALYSIS",
    "PROMPT_AGENT_07_IKIGAI",
    "PROMPT_AGENT_07_IKIGAI_ANALYSIS"
]
